version: "3.8"

services:
    db:
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: testUser
            POSTGRES_PASSWORD: testPassword
            POSTGRES_DB: testDatabase
    adminer:
        image: adminer
        restart: unless-stopped
        links:
            - db
        depends_on:
            - db
        ports:
            - 8080:8080
