version: "3.8"

services:
    app:
        build:
            context: .
        ports:
            - 8000:8000

    sql:
        image: postgres
        restart: unless-stopped
#        ports:
#            - 5432:5432
        environment:
            POSTGRES_USER: testUser
            POSTGRES_PASSWORD: testPassword
            POSTGRES_DB: testDatabase
    adminer:
        image: adminer
        restart: unless-stopped
        links:
            - sql
        depends_on:
            - sql
        ports:
            - 8080:8080
